name: auto_tag
on:
  push:
    branches:
      - 'release_v_*' # 仅在以 'release_v_' 开头的分支推送时触发
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'auto_tag'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Execute Tag Creation Script
      run: |
       pnpm i
       pnpm run create:tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
