name: Create Release Tag
on:
  push:
    branches:
      - 'release_v_*' # 仅在以 'release_v_' 开头的分支推送时触发

jobs:
  create_tag:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute Tag Creation Script
      run: |
        if [[ $GITHUB_REF == refs/heads/release_v_* ]]; then
          ./create_tag.sh
        fi
      env:
        VERSION: ${{ github.ref }}
