name: ci-branch-release
on:
  push:
    branches:
      - release_v_*
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'ci-branch-release'

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm install 
    - run: |
       pnpm run ci:branch-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
