name: ci-master 
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'ci-master'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Determine Branch Type
      run: |
        if [[ "${{ github.event.pull_request.head.ref }}" =~ ^release/v_.*$ ]]; then
          echo "This is a release branch."
        else
          echo "This is a non-release branch. Ending workflow."
          exit 0  # Exit successfully to end the workflow
        fi

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
        node-version: 'lts/hydrogen'
    - run: pnpm install

    - name: Execute Tag Creation Script
      run: |
       pnpm run release --patch --git  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
